### PR TITLE
Latin

### PR DESCRIPTION
**Pull request by EbenSorkin**

### CODE REVIEW

**Comment by graphicore** [comment]
I see that you created new files and folders in the top level of the repository: `Jomhuria-Regular.ufo`, `jomhuria-latin.sfdir` `Jomhuria-Regular.otf` and also some files below top level e.g. `sources/JomhuriaLatin-Regular.vfb`

It's going to be a problem for the me to pull this, especially the top level files I won't accept.

However, I guess that you are working with Fontlab, hence the `vfb`files and that the `sources/JomhuriaLatin-Regular.ufo` is not your primary working file. It's OK for you to work in Fontlab (or anything), but the project depends on FLOSS tools (Fontforge, `UFO`) and thus the main (authorative) input will stay the `UFO` file. If it's better for you to keep a vfb file around (for what reason?) than to just import/export the ufo, that's ok. However, if the `UFO` changes (by someone else) you should reimport it into your vfb file, to stay up to date and to not cause regressions.  That way we can communicate in both directions, as well.
I hope there is no loss of data/setup etc. involved when importing the `UFO` into Fontlab instead of keeping the `vfb` around. If there is loss, please let me know in what regard. It's of general interest to me and also important to know if we are going to lose valuable information when deleting the `vfb` files, once you are done.

The `otf` file is also rather uninteresting for me at this point. The final font will be build with Fontforge/Sortsmill, in the end, as it is at the moment.

**Comment by davelab6** [comment]
Use http://blog.fontlab.com/font-utility/vfb2ufo/

**Comment by EbenSorkin** [comment]
On Jun 24, 2015, at 11:51 AM, Lasse Fister notifications@github.com wrote:

> I see that you created new files and folders in the top level of the repository: Jomhuria-Regular.ufo, jomhuria-latin.sfdir Jomhuria-Regular.otf and also some files below top level e.g. sources/JomhuriaLatin-Regular.vfb
> 
> It's going to be a problem for the me to pull this, especially the top level files I won't accept.
> 
> However, I guess that you are working with Fontlab, hence the vfbfiles and that the sources/JomhuriaLatin-Regular.ufo is not your primary working file. It's OK for you to work in Fontlab (or anything), but the project depends on FLOSS tools (Fontforge, UFO) and thus the main (authorative) input will stay the UFO file.
> 
> thats fine. fontlab let’s me do some things faster ( spacing and systemic adjustments to spacing) than any other tool so I like to use it for those things.
> 
> If it's better for you to keep a vfb file around (for what reason?) than to just import/export the ufo, that's ok.
> 
> That’s what’ll do.
> However, if the UFO changes (by someone else) you should reimport it into your vfb file, to stay up to date and to not cause regressions. That way we can communicate in both directions, as well.
> 
> That makes perfect sense. Yes.
> 
> I hope there is no loss of data/setup etc. involved when importing the UFO into Fontlab instead of keeping the vfb around.
> 
> Happily there isn’t.
> 
> If there is loss, please let me know in what regard. It's of general interest to me and also important to know if we are going to lose valuable information when deleting the vfb files, once you are done.
> 
> The otf file is also rather uninteresting for me at this point. The final font will be build with Fontforge/Sortsmill, in the end, as it is at the moment.

That’s fine since Fontforge imports UFOs well.

The stuff in the files I have is only there as a side effect of my process assesing what needs to be done.

I’ll work on getting you the remaining info now so that we can be officially started.

-e.

**Comment by EbenSorkin** [comment]
that is what I use. It seems quite good.

-e.

**Comment by davelab6** [comment]
Close this?

**Comment by graphicore** [comment]
yes

**Pull request closed without merging**
